version: '3'
services:
  app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:13.0-alpine'
    restart: always
    env_file:
      - .env
    volumes:
      - shop_api_db:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

volumes:
  shop_api_db: